// src/views/ClassDetails/ClassDetails.jsx
import { useRoute } from 'vue-router';
import { DisplayClass } from '@/components/DisplayClass';

export const ClassDetails = {
  name: 'ClassDetails',
  setup() {
    const route = useRoute();

    const renderClassContent = () => (
      <div>
        {
          <DisplayClass
            params={route.params}
          />
        }
      </div>
    );

    return () => (
      renderClassContent()
    );
  }
};

// src/views/ClassDetails.vue
<template>
  <div>
    <div>
      Class name: {{ feature }}
    </div>
  </div>
</template>

<script>
  import { useRoute } from 'vue-router';
  import { computed } from 'vue';

  export default {
    name: 'ClassDetails',
    setup() {
      const route = useRoute();
      const feature = computed(() => route.params.class);
      return {
        feature
      };
    }
  };
</script>

<style scoped>

</style>
